dist: xenial
language: cpp
script: CXX=$SCONS_CXX scons $SCONSFLAGS && ./ptwalker
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
    packages:
      - scons
      - gcc-8
      - g++-8
      - clang-7
      - llvm-7-dev
env:
  - SCONS_CXX=g++-8
  - SCONS_CXX=clang++-7
  - SCONS_CXX=clang++-7 SCONSFLAGS="--lto --asan --ubsan"

before_script:
  - sudo mkdir -p /usr/include/catch2
  - sudo curl -L https://github.com/catchorg/Catch2/releases/download/v2.5.0/catch.hpp -o /usr/include/catch2/catch.hpp
